version: '3.8'

services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_HTTP_ADDR: "0.0.0.0:5000"
    volumes:
      - registry_data:/var/lib/registry
    restart: unless-stopped

volumes:
  registry_data: 