name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Configure podman for local registry
        run: |
          mkdir -p ~/.config/containers
          cat > ~/.config/containers/registries.conf << 'EOF'
          unqualified-search-registries = ["docker.io"]
          
          [[registry]]
          location = "localhost:5000"
          insecure = true
          EOF

      - name: Build
        run: |
          make build

      - name: Setup test registry
        run: |
          ./scripts/setup-test-registry.sh

      - name: Run tests
        run: |
          go test -v

      - name: Cleanup test registry
        if: always()
        run: |
          ./scripts/cleanup-test-registry.sh

      - name: Build all platforms
        run: |
          make build-all

      - name: List binaries
        run: |
          ls -la bin/ 