name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: |
          make build

      - name: Run tests
        run: |
          make test

      - name: Build all platforms
        run: |
          make build-all

      - name: List binaries
        run: |
          ls -la bin/ 